spring:
  application:
    name: @application.name@

  datasource:
    url: ${SPRING_DATASOURCE_URL:@application.database.url@}
    username: ${SPRING_DATASOURCE_USERNAME:@application.database.username@}
    password: ${SPRING_DATASOURCE_PASSWORD:@application.database.password@}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: @application.database.hibernate.ddl@

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    url: ${SPRING_DATASOURCE_URL:@application.database.url@}
    user: ${SPRING_DATASOURCE_USERNAME:@application.database.username@}
    password: ${SPRING_DATASOURCE_PASSWORD:@application.database.password@}
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: false

