spring:
  application:
    name: @application.name@

  datasource:
    url: @application.database.url@
    username: @application.database.username@
    password: @application.database.password@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: @application.database.hibernate.ddl@

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    url: @application.database.url@
    user: @application.database.username@
    password: @application.database.password@
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: false

